# Denoise Studio — one-click start (FastAPI backend + Vite frontend)
# Usage:
#   .\start-webapp.ps1              # start both
#   .\start-webapp.ps1 -InstallDeps # install pip/npm deps first
#   .\start-webapp.ps1 -Stop        # stop processes on ports 8000 / 5173

[CmdletBinding()]
param(
    [switch]$InstallDeps,
    [switch]$NoBrowser,
    [switch]$Stop
)

$ErrorActionPreference = "Stop"

$WebAppRoot = $PSScriptRoot
$DenoiseRoot = (Resolve-Path (Join-Path $WebAppRoot "..")).Path
$DemoRoot = (Resolve-Path (Join-Path $WebAppRoot "..\..\..")).Path
$BackendDir = Join-Path $WebAppRoot "backend"
$FrontendDir = Join-Path $WebAppRoot "frontend"
$EnvFile = Join-Path $WebAppRoot ".env"
$EnvExample = Join-Path $WebAppRoot ".env.example"

function Import-DotEnv {
    param([string]$Path)
    if (-not (Test-Path $Path)) { return }
    Get-Content -LiteralPath $Path -Encoding UTF8 | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#")) { return }
        $eq = $line.IndexOf("=")
        if ($eq -lt 1) { return }
        $name = $line.Substring(0, $eq).Trim()
        $value = $line.Substring($eq + 1).Trim()
        if ($value.StartsWith('"') -and $value.EndsWith('"')) {
            $value = $value.Substring(1, $value.Length - 2)
        }
        Set-Item -Path "Env:$name" -Value $value
    }
}

function Test-CommandExists {
    param([string]$Name)
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Stop-PortListeners {
    param([int[]]$Ports)
    foreach ($port in $Ports) {
        $conns = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
        foreach ($c in $conns) {
            $procId = $c.OwningProcess
            if ($procId -and $procId -ne 0) {
                Write-Host "Stopping PID $procId (port $port)..." -ForegroundColor Yellow
                Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue
            }
        }
    }
}

function Ensure-EnvFile {
    if (Test-Path $EnvFile) { return }
    if (-not (Test-Path $EnvExample)) {
        throw ".env.example not found at $EnvExample"
    }
    Copy-Item -LiteralPath $EnvExample -Destination $EnvFile
    Write-Host "Created .env from .env.example" -ForegroundColor Cyan
}

function Ensure-FrontendEnv {
    $localEnv = Join-Path $FrontendDir ".env.local"
    if (Test-Path $localEnv) { return }
    $apiBase = if ($env:VITE_API_BASE_URL) { $env:VITE_API_BASE_URL } else { "http://127.0.0.1:8000" }
    @(
        "# Auto-generated by start-webapp.ps1"
        "VITE_API_BASE_URL=$apiBase"
    ) | Set-Content -LiteralPath $localEnv -Encoding UTF8
    Write-Host "Created frontend/.env.local (VITE_API_BASE_URL=$apiBase)" -ForegroundColor Cyan
}

if ($Stop) {
    Stop-PortListeners -Ports @(8000, 5173)
    Write-Host "Stopped listeners on ports 8000 and 5173 (if any)." -ForegroundColor Green
    exit 0
}

Write-Host ""
Write-Host "=== Denoise Studio ===" -ForegroundColor Cyan
Write-Host "Repo root : $DemoRoot"
Write-Host "Web app   : $WebAppRoot"
Write-Host ""

if (-not (Test-CommandExists "python")) {
    throw "Python not found in PATH. Install Python 3.10+ or activate your conda env first."
}
if (-not (Test-CommandExists "npm")) {
    throw "npm not found in PATH. Install Node.js 18+ first."
}

Ensure-EnvFile
Import-DotEnv -Path $EnvFile

# Defaults aligned with .env.example (DeepFilterNet3 via conda dfnet311)
if (-not $env:DEEPFILTER_CONDA_ENV) { $env:DEEPFILTER_CONDA_ENV = "dfnet311" }
if (-not $env:APP_HOST) { $env:APP_HOST = "0.0.0.0" }
if (-not $env:APP_PORT) { $env:APP_PORT = "8000" }
if (-not $env:VITE_API_BASE_URL) { $env:VITE_API_BASE_URL = "http://127.0.0.1:8000" }
if (-not $env:APP_DATA_DIR) {
    $env:APP_DATA_DIR = (Join-Path $DemoRoot "analysis\denoise_selection\webapp\data")
}

Ensure-FrontendEnv

if ($InstallDeps) {
    Write-Host "Installing backend dependencies..." -ForegroundColor Cyan
    & python -m pip install -r (Join-Path $BackendDir "requirements.txt")
    Write-Host "Installing frontend dependencies..." -ForegroundColor Cyan
    Push-Location $FrontendDir
    try { npm install } finally { Pop-Location }
}

if (-not (Test-Path (Join-Path $FrontendDir "node_modules"))) {
    Write-Host "node_modules missing — run: .\start-webapp.ps1 -InstallDeps" -ForegroundColor Yellow
    Write-Host "Attempting npm install..." -ForegroundColor Cyan
    Push-Location $FrontendDir
    try { npm install } finally { Pop-Location }
}

# Backend must run with cwd = repo root (distill checkpoint & data paths)
$backendPort = [int]$env:APP_PORT
Stop-PortListeners -Ports @($backendPort)

$backendCmd = @"
Set-Location -LiteralPath '$DemoRoot'
`$env:DEEPFILTER_CONDA_ENV = '$($env:DEEPFILTER_CONDA_ENV)'
`$env:APP_HOST = '$($env:APP_HOST)'
`$env:APP_PORT = '$($env:APP_PORT)'
`$env:APP_DATA_DIR = '$($env:APP_DATA_DIR)'
`$env:CORS_ORIGINS = '$($env:CORS_ORIGINS)'
Write-Host '=== Backend (FastAPI) ===' -ForegroundColor Green
Write-Host "CWD: `$PWD"
Write-Host "API: http://127.0.0.1:$backendPort/docs"
Write-Host "DeepFilter conda env: `$env:DEEPFILTER_CONDA_ENV"
python -m uvicorn app.main:app --reload --host `$env:APP_HOST --port $backendPort --app-dir '$BackendDir'
"@

Write-Host "Starting backend on port $backendPort ..." -ForegroundColor Green
Start-Process -FilePath "powershell.exe" -ArgumentList @("-NoExit", "-NoLogo", "-Command", $backendCmd) | Out-Null

Start-Sleep -Seconds 2

$frontendCmd = @"
Set-Location -LiteralPath '$FrontendDir'
`$env:VITE_API_BASE_URL = '$($env:VITE_API_BASE_URL)'
Write-Host '=== Frontend (Vite) ===' -ForegroundColor Green
Write-Host "API base: `$env:VITE_API_BASE_URL"
Write-Host 'UI: http://localhost:5173'
npm run dev
"@

Write-Host "Starting frontend on http://localhost:5173 ..." -ForegroundColor Green
Start-Process -FilePath "powershell.exe" -ArgumentList @("-NoExit", "-NoLogo", "-Command", $frontendCmd) | Out-Null

if (-not $NoBrowser) {
    Start-Sleep -Seconds 2
    Start-Process "http://localhost:5173"
}

Write-Host ""
Write-Host "Both services launched in separate windows." -ForegroundColor Green
Write-Host "  Frontend : http://localhost:5173"
Write-Host "  Backend  : http://127.0.0.1:$backendPort/docs"
Write-Host "  Stop     : .\start-webapp.ps1 -Stop"
Write-Host ""
